# This file was generated by GoReleaser. DO NOT EDIT.
class Kapo < Formula
  desc "Wrap any command in a status socket"
  homepage "https://github.com/sampointer/kapo"
  version "1.1.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sampointer/kapo/releases/download/v1.1.4/kapo_1.1.4_Darwin_x86_64.tar.gz"
    sha256 "144e2cdbb63d087fa8640e167f8e41e69187324afabacd07d92617d47103d547"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sampointer/kapo/releases/download/v1.1.4/kapo_1.1.4_Linux_x86_64.tar.gz"
    sha256 "1d724bc9359bb068a2fc9fa49e652724d0b14037bc8164e3ca0f88d8aedbe4ab"
  end

  def install
    bin.install "kapo"
  end
end
